# To run locally
# npx @techdocs/cli serve -v -c ./mkdocs.yml
# 
site_name: 'collector-configurator Internal Documentation'
repo_url: https://github.com/grafana/collector-configurator
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.sections

plugins:
  - techdocs-core
